---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
  labels:
    app: productcatalogue
spec:
  selector:
    app: productcatalogue
  ports:
  - protocol: TCP
    port: 8020
    name: http