apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager
spec:
  spec:
  selector:
    matchLabels:
      app: stockmanager
  replicas: 1
  template:
    metadata:
      labels:
        app: stockmanager
    spec:
      containers:
      - name: stockmanager
        image: lepolesa/stockmanager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8030
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8030
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 1
        # resources:
        #   requests:
        #     cpu: "1"
        #     memory: "1G"
        #   limits:
        #     cpu: "2"
        #     memory: "2Gi"