apiVersion: v1
kind: Service
metadata:
  name: stockmanager
  labels:
    app: stockmanager
spec:
  type: ClusterIP
  selector:
    app: stockmanager
  ports:
  - protocol: TCP
    port: 8030
    name: http
